### ISSUE TITLE
How to set inputs and outputs if examples have different shapes

### ISSUE THREAD

**Issue by jnd77** [google-research/tensorflow-coder#1]
Hi.
Thanks a lot for this great tool.
I'm trying to use it for a simple op, where the input is a Tensor of shape (num_boxes, 4) - where num_boxes can be any value, and the output would have a fixed shape (10, 4). Basically, it would either pad if num_boxes is less than 10, or slice the first 10 otherwise.

Am not clear how I could set various examples for inputs, since they would have different shapes.

Could you please give me a hint ?

Thanks a lot ! :)

**Comment by kensens** [comment]
Hi, currently TF-Coder only supports one input-output example at a time, so it wouldn't be possible to use TF-Coder to solve this problem at the moment. However, you can try to solve each individual case separately (num_boxes less than 10, or num_boxes greater than 10) and combine them with your own if statement.
