### ISSUE TITLE
Performance issues in tf_coder/datasets/github/data_loader.py(P2)

### ISSUE THREAD

**Issue by DLPerf** [google-research/tensorflow-coder#3]
Hello,I found a performance issue in the definition of `load_data` ,
tf_coder/datasets/github/data_loader.py,
[dataset = dataset.map(parse_example_proto)](https://github.com/google-research/tensorflow-coder/blob/4356977eec157b0a90c97cd79116c7eaef8447d0/tf_coder/datasets/github/data_loader.py#L70) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by kensens** [comment]
Thank you for your comment, but the affected code is not used often, so this is low priority for us.
