### ISSUE TITLE
tensorflow/core/framework/tensor_shape.cc:356] Check failed: d >= 0 (0 vs. -1)

### ISSUE THREAD

**Issue by liujqian** [google-research/tensorflow-coder#8]
```
 def get_problem():
    """Specifies a problem to run TF-Coder on. Edit this function!"""
    # A dict mapping input variable names to input tensors.
    inputs = {
        'rows': [1, 2, 3],
    }
    # The corresponding output tensor.
    output = [0, 100, 200]
    # A list of relevant scalar constants, if any.
    constants = [10, 1]
    # An English description of the tensor manipulation.
    description = 'subtract one and multiply by one hundred'
    return inputs, output, constants, description
```
This problem will break and cause the Python environment to shut down:
`2024-12-10 09:23:12.332684: F tensorflow/core/framework/tensor_shape.cc:356] Check failed: d >= 0 (0 vs. -1)
Fatal Python error: Aborted`
Is this some kind of compatibility issue? If so, which version of TensorFlow should be used?

**Comment by kensens** [comment]
This is a problem in core TensorFlow. Unfortunately TensorFlow does abort in rare cases which makes it difficult to search over TensorFlow expressions.

By adding `'printing.all_apply': True` in the settings, I observe:

```
...
Applying tf.transpose(a, perm) on arguments: ['tf.where(rows)', '(-1, 0)']
2024-12-16 15:21:27.252299: F tensorflow/core/framework/tensor_shape.cc:356] Check failed: d >= 0 (0 vs. -1)
Aborted (core dumped)
```

So, the abort happens as TF-Coder attempts to evaluate `tf.transpose(tf.where(rows), (-1, 0))` during its search. Similarly, TensorFlow also aborts on `tf.transpose([[0]], [-1, 0])`.

Please raise this abort to the TensorFlow team.

**Comment by liujqian** [comment]
Hi thanks for replying. Can you please share something like a requirements.txt showing the versions of dependencies compatible with tfcoder? Thanks!

**Comment by kensens** [comment]
Please see [setup.py](https://github.com/google-research/tensorflow-coder/blob/master/setup.py#L22). TF-Coder is compatible with all recent versions of TensorFlow, but unfortunately we inherit some of TensorFlow's bugs. I don't know when this particular bug first appeared in TensorFlow.
